# Netlify Configuration for Flutter Web
[build]
  # Base directory where the project is located
  base = "frontend"

  # Build command with Flutter installation
  command = "chmod +x build.sh && ./build.sh"

  # Output directory (relative to base)
  publish = "build/web"

  # Build environment
  [build.environment]
    # Set Flutter to use stable channel
    FLUTTER_CHANNEL = "stable"
    # Backend API URL (Railway)
    API_URL = "https://kinrai-d-backend.up.railway.app"

# Redirect rules for Flutter SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache service worker
[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
