[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildContext = "."

[deploy]
startCommand = "node dist/src/main"
healthcheckPath = "/api/v1"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
